apiVersion: v1
kind: ServiceAccount
metadata:
  name: blogpost-operator-sa
  namespace: blogposts

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: blogpost-operator
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["merixstudio.com"]
    resources: ["blogposts", "blogpostrequests"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["merixstudio.com"]
    resources: ["blogposts/status", "blogpostrequests/status"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: blogpost-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: blogpost-operator
subjects:
- kind: ServiceAccount
  name: blogpost-operator-sa
  namespace: blogposts

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: blogpost-aggregate-edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - merixstudio.com
  resources:
  - blogposts
  - blogpostrequests
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: blogpost-aggregate-view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - merixstudio.com
  resources:
  - blogposts
  - blogpostrequests
  verbs:
  - get
  - list
  - watch
