apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: blogposts.merixstudio.com
spec:
  group: merixstudio.com
  version: v1
  scope: Namespaced
  names:
    plural: blogposts
    singular: blogpost
    kind: BlogPost
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            title: 
              type: string
            body:
              type: string
          required:
          - title
          - body
          type: object
  subresources:
    status: {}
