apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: blogpostrequests.merixstudio.com
spec:
  group: merixstudio.com
  version: v1
  scope: Namespaced
  names:
    plural: blogpostrequests
    singular: blogpostrequest
    kind: BlogPostRequest
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            title: 
              type: string
            paragraphs:
              type: integer
          required:
          - title
          type: object
  subresources:
    status: {}
